# Generated by Django 5.1.3 on 2025-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(),
        ),
    ]
