# Generated by Django 5.0.6 on 2025-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_remove_tag_name_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='default-tag', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
